### ISSUE TITLE
Site traffic metrics

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#1018]
We would like to be able to track site visits of the GO sub-pages.
We need the following metrics: (TBD)
- # of visitors per geography, domain of GO in a given timeframe
- # of visitors per geography, domain of the subpage
- # of unique visitors
- tbd

**Comment by gulfaraz** [comment]
Requested for Azure resource in #1026

**Comment by nanometrenat** [comment]
Hi @tovari am forwarding an old thread now - other prior requests have been to track downloads (e.g. of the docs on emergency pages), and to track people who just go to GO in order to go on somewhere else (e.g. solely clicking on 'create a report' to go on to the Indicator and Financial kobo forms - noting that Kobo then automatically redirects them back to GO after they've filled in those forms).  Other prior requests were to be able to see who looks at which tab within an emergency page, and who looks while logged in vs not logged in (bearing in mind that IFRC users see more info than RCRC users, who in turn see more info than users who aren't logged in).  Cheers and good luck!

**Comment by gulfaraz** [comment]
[It appears the go-frontend has been using google analytics since 2 Aug 2018.](https://github.com/IFRCGo/go-frontend/pull/379)

Do we have still have access to the [google account and/or tracking id used here](https://github.com/IFRCGo/go-frontend/blob/develop/public/index.html#L45-L51)?

Reference: https://github.com/IFRCGo/go-frontend/issues/370

@tovari @LukeCaley @batpad

**Comment by tovari** [comment]
@gulfaraz , we agreed that we keep using G Analytics.

**Comment by gulfaraz** [comment]
@tovari I'll make a PR to remove Application Insights from the go-api. I've already closed the open PR on the go-frontend.

**Comment by batpad** [comment]
@gulfaraz - hmm .. doesn't the API code give us a bit more data than what is captured in Google Analytics? Or is that not the case? If it does, I'd consider / suggest leaving the backend code, so that we continue to gather data that isn't otherwise being captured?

**Comment by batpad** [comment]
Clarified with @gulfaraz on voice: we will remove App Insights, but replace it with Google Analytics on the backend API.

**Comment by gulfaraz** [comment]
@jhenshall and I discussed the use of [Google Tag Manager](https://tagmanager.google.com/) for the go-frontend. Tag Manager is not a replacement for Google Analytics! It captures basic user interactions without the need to explicitly code it.

However, this is a second dependency that needs separate approval.

If we choose to use Google Analytics **WITH** Tag Manager,
- typically used by data analytics teams and can be hard to navigate for others
- allows us to start collecting analytics data for many basic user interactions like clicks, scroll
- complex interactions have to be coded by a developer

If we choose to use Google Analytics **WITHOUT** Tag Manager,
- a developer should be able to navigate Google Analytics but is limited due to a lack of expertise
- need to define interactions we are interested in before collecting
- all interactions have to be coded by a developer

I am concerned that we don't have an analytics expert on the Go team for maintaining the Tag Manager. The alternative is to have a clear plan and risk losing the data until that plan is ready.

@tovari @batpad @LukeCaley

**Comment by gulfaraz** [comment]
@batpad I'm unable to find a package that tracks API calls and sends the logs to Google Analytics. Do you know any packages that meet our need?

Now, the options are,
1. Use Application Insights for go-api and Google Analytics for go-frontend.
2. Build a middleware and maintain it ourselves.

**Comment by gulfaraz** [comment]
@jhenshall I'm unable to find this option in the [IFRC go-frontend Google Analytics](https://analytics.google.com/analytics/web/?authuser=0#/report-home/a84297335w166090858p166616198)

<img width="931" alt="Screenshot 2021-05-27 at 16 46 12" src="https://user-images.githubusercontent.com/3880591/119847421-3fbf9e00-bf0b-11eb-9fe6-ef1a0ac97b0e.png">

Are you familiar with this setting and maybe correct me if I'm looking at the wrong place?

**Comment by jhenshall** [comment]
Hey @gulfaraz - this is the new version Google Analytics 4 (GA4). I'm not familiar with it but would be happy to look in more detail. As you can see, it would be great for tracking a lot of things by default but would mean we need to add new tracking code and the data would start from scratch.

**Comment by gulfaraz** [comment]
@jhenshall

> this is the new version Google Analytics 4 (GA4).

This makes sense.

> I'm not familiar with it but would be happy to look in more detail.

This would be great.

> As you can see, it would be great for tracking a lot of things by default

I agree

> but would mean we need to add new tracking code and the data would start from scratch.

[This article suggest that we may not have to start from scratch](https://support.google.com/analytics/answer/9744165?hl=en)

**Comment by batpad** [comment]
> Build a middleware and maintain it ourselves.

@gulfaraz I was able to find something like https://pypi.org/project/django-google-analytics-app/ but cannot vouch for it :)

I, unfortunately, have never used Google Analytics for API usage tracking, so don't know for sure. @thenav56 have you ever had to do this?

Especially if we don't find something off-the-shelf here, I'd seriously consider just using Azure Insights for the API usage tracking? I some-how feel this may also give us more flexibility down the line in tracking things, though perhaps we can get the same with Google. Let's discuss this before going too deep here.

**Comment by gulfaraz** [comment]
> I was able to find something like https://pypi.org/project/django-google-analytics-app/ but cannot vouch for it :)

I tried this yesterday. I can vouch against it.

> I'd seriously consider just using Azure Insights for the API usage tracking

100% agree.

**Comment by thenav56** [comment]
> > Build a middleware and maintain it ourselves.
> 
> @gulfaraz I was able to find something like https://pypi.org/project/django-google-analytics-app/ but cannot vouch for it :)
> 
> I, unfortunately, have never used Google Analytics for API usage tracking, so don't know for sure. @thenav56 have you ever had to do this?
> 
> Especially if we don't find something off-the-shelf here, I'd seriously consider just using Azure Insights for the API usage tracking? I some-how feel this may also give us more flexibility down the line in tracking things, though perhaps we can get the same with Google. Let's discuss this before going too deep here.

I also agree with using Azure Insights.

**Comment by batpad** [comment]
@gulfaraz are there any next actions here? Is there still things to be done to get more fine-grained data from the frontend usage?

Just trying to do some ticket gardening ..

**Comment by gulfaraz** [comment]
> are there any next actions here?

Not that I'm aware of. I was supposed to set up tracking in Azure Insights but the old Google Analytics setup already tracked the same information. We finally decided to continue using Google Analytics.

> Is there still things to be done to get more fine-grained data from the frontend usage?

There was some discussion regarding fine-grained usage but nothing tangible yet. I suggest creating new items for those new requirements if they come up.

> Just trying to do some ticket gardening ..

Thank you!
