### ISSUE TITLE
IMS data transfer

### ISSUE THREAD

**Issue by gulfaraz** [IFRCGo/go-api#1150]
_I'm creating this feature request on behalf of @JonathanGarro who sent the details via email._

A step beyond the [Excel upload](https://github.com/IFRCGo/go-api/issues/1149) would be having direct connections with teams’ existing portfolio management systems. While each NS system would be different, I’d be interested in how we can explore ways to at least set teams up to utilize a POST or PATCH method. We can use my NS’s system to test that process.

**Comment by JonathanGarro** [comment]
Documenting notes from my discussion on 2021-08-06 with @gulfaraz on this issue:

- **What we mean by sync:** This is _not_ a bi-directional sync where data is being passed from an NS IMS to GO and vice versa. This is only one direction: from NS IMS to GO _only_.
- **Expected output:** This issue would not be building towards a single solution wherein any NS with an IMS could turn a key and sync their data. We anticipate the output here being more focused on establishing a framework to help teams with these databases understand what they have to do to get their data to sync (since each instance will have different requirements without the possibility for a "one-size-fits-all" approach). 
- **Expected scope:** This should focus on the 3W tool first with option to expand to other elements in the future, depending on how this testing goes. 
- **High-level plan moving forward:** Jonathan to build a simple example of a report from his database that maps the relevant fields on the 3W. Gulfaraz and Jonathan to test solutions for pushing that data to GO.

**Comment by gulfaraz** [comment]
@JonathanGarro I've sent via email a python script that does a basic read-write of the 3W projects.

The script assumes a local CSV database and required manually setting an auth token.

I want to check with you if this is the right direction before continuing on it.

**Comment by gulfaraz** [comment]
Moved to conversation to #804
