### ISSUE TITLE
Surge: missing sending NS info at certain deployments

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#1241]
Some of the deployed personnel has no sending NS information available in GO.
https://go.ifrc.org/deployments/personnel/all

![image](https://user-images.githubusercontent.com/68283148/144624211-17bc253b-fa1f-4657-ba3f-7c5673f4c882.png)

Please investigate the cause of the issue.
Thanks!

cc: @anamariaescobar

**Comment by anamariaescobar** [comment]
Hi @tovari, this is due to a missmatch in the list of NS stored in Molnix. We have been fixing it case by case, but I will definetly ask the surge team for a list to do the metch once and for all. We are changing Molnix to match GO, so no action required by anyone except from me. @batpad @szabozoltan69
