### ISSUE TITLE
[PROD] Show only active appeals in emergency page key figures

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-api#1328]
## Issue
There is an emergency, no. 544: https://go.ifrc.org/emergencies/544
There are 2 appeals, which belongs to it: one of them is in status closed, the other is active.
We should not use the closed appeal.
![kép](https://user-images.githubusercontent.com/6050643/155189606-e272334f-e797-4cd7-b176-6d9ec0024ca8.png)
![kép](https://user-images.githubusercontent.com/6050643/155189688-eac7624e-4165-4609-bb60-785345b09653.png)
![kép](https://user-images.githubusercontent.com/6050643/155189798-9ae71db8-702e-45da-8fca-766ec82b5aed.png)
3400000.00 + 3375048.00 = 6775048.00
3063539.60 + 1698470.96 = 4762010.56

To exclude the closed one we should modify EventViewset.
If I put 3 "excluding" rows, like these,
```
for ind, apl in enumerate(serializer.data['appeals']):
    if apl['status'] != 0:
        del serializer.data['appeals'][ind]
```
 before https://github.com/IFRCGo/go-api/blob/develop/api/drf_views.py#L424 , then I receive:
![kép](https://user-images.githubusercontent.com/6050643/155190219-ee4bec72-9a74-421a-9e75-702a848f08eb.png)
But this solution is not nice. Please advice me a nicer one, @batpad @thenav56 

(It would be much nicer to insert a filter to https://github.com/IFRCGo/go-api/blob/develop/api/drf_views.py#L376, but I could not.)

**Comment by thenav56** [comment]
@szabozoltan69 Since this is not aggregated data, you can filter out the data on the client side. If a closed appeal is never needed to be sent through view then you need to custom source on the serializer which filters out. Or you can add another field in the serializer which will send those data as a field where you can define the logic to filter out and aggregate.

I would recommend doing this on the client-side for now.

**Comment by szabozoltan69** [comment]
In local environment I tried it, filtering on frontend side (according to @thenav56 advice).
![kép](https://user-images.githubusercontent.com/6050643/155370862-fd1c0f11-5184-4555-8ee3-3f76b824fce6.png)
