### ISSUE TITLE
Implement generalized cache for API responses

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#1460]
We should setup a caching layer for API responses that we can tweak per endpoint based on needs.

Currently, ever API request hits the database, and for a lot of these requests, we can cache responses for some time, to reduce load on the database and drastically improve site performance.

Django has a relatively decent cache framework that we can use, but I'd be super interested in seeing if this can be implemented at the CDN level without having to touch the application code. (cc @MartonNagyATOS )

Let's discuss approaches here and hopefully are able to implement something soon and then iterate.

cc @szabozoltan69 @tovari @frozenhelium

**Comment by MartonNagyATOS** [comment]
Hi All,

Without knowing many details, in general it is possible to tunnel the API calls through CDN.
CDN is not just caching the data, but deployed to edge servers, meaning that the client calls will be served by an edge server that is closest to client. (lower latency and roundtrip time)
If one of the edge servers fails, it automatically switches to the next closest location, so it also increases the availability for the cached responses.
And there are many other options at the CDN level, like response compression to reduce the traffic if the user agent supports it. (All modern browser support it.)

Marton

From: Sanjay Bhangar ***@***.***>
Sent: Tuesday, 21 June 2022 13:24
To: IFRCGo/go-api ***@***.***>
Cc: Nagy, Marton ***@***.***>; Mention ***@***.***>
Subject: [IFRCGo/go-api] Implement generalized cache for API responses (Issue #1460)


Caution! External email. Do not open attachments or click links, unless this email comes from a known sender and you know the content is safe.

We should setup a caching layer for API responses that we can tweak per endpoint based on needs.

Currently, ever API request hits the database, and for a lot of these requests, we can cache responses for some time, to reduce load on the database and drastically improve site performance.

Django has a relatively decent cache framework that we can use, but I'd be super interested in seeing if this can be implemented at the CDN level without having to touch the application code. (cc @MartonNagyATOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMartonNagyATOS&data=05%7C01%7Cmarton.nagy%40atos.net%7C730b4f448c834a4cac5108da53789589%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637914074754115481%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1OZjtM54aEjLgl9Dke9lssHNa2MozbHdKA79%2B9VBhAU%3D&reserved=0> )

Let's discuss approaches here and hopefully are able to implement something soon and then iterate.

cc @szabozoltan69<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fszabozoltan69&data=05%7C01%7Cmarton.nagy%40atos.net%7C730b4f448c834a4cac5108da53789589%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637914074754115481%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ByOeIMF6vJBKg5m7kHaH%2FTXGD5Qw4EYVy%2F34H%2B295IY%3D&reserved=0> @tovari<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftovari&data=05%7C01%7Cmarton.nagy%40atos.net%7C730b4f448c834a4cac5108da53789589%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637914074754115481%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IXHh4Jv0rLJWFoSV3U4gDb8eo28yIkqmbS1tQfma4Ok%3D&reserved=0> @frozenhelium<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffrozenhelium&data=05%7C01%7Cmarton.nagy%40atos.net%7C730b4f448c834a4cac5108da53789589%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637914074754115481%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Cr4fKlk0JQADKk6VvPbN9JTaBNtN34l18juqT8Ezu48%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FIFRCGo%2Fgo-api%2Fissues%2F1460&data=05%7C01%7Cmarton.nagy%40atos.net%7C730b4f448c834a4cac5108da53789589%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637914074754115481%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6vvqv7pTDFuIh2gDn7Vxn3cXKtUkjfSKfi5zAwhYhvw%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATL33DM3FMYW7OYRY7FQQH3VQGQ5ZANCNFSM5ZL7FDUA&data=05%7C01%7Cmarton.nagy%40atos.net%7C730b4f448c834a4cac5108da53789589%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637914074754115481%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9JTbuMqEdvo0hsuKIvWu6ZSyVkAoKTMXZyC%2FQeD8OJw%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

Important Note: This e-mail and the documents attached are confidential and intended solely for the addressee; it may also be privileged. If you receive this e-mail in error, please notify the sender immediately and destroy it. As its integrity cannot be secured on the Internet, the Atos group liability cannot be triggered for the message content. Although the sender endeavors to maintain a computer virus-free network, the sender does not warrant that this transmission is virus-free and will not be liable for any damages resulting from any virus transmitted.

**Comment by batpad** [comment]
Based on in-person discussion, it's probably a good idea to go ahead and implement application level caching, which will still be useful even if we implement CDN level caching down the line.

We would use the Django Cache framework: https://docs.djangoproject.com/en/4.1/topics/cache/

This should be fairly easy to setup. The main thing would be to figure out how long we want to cache different entity types for.

A good place to start would be to look at all requests made on the home-page, and make sure they all have some level of caching.

cc @tovari @thenav56 @szabozoltan69 @tnagorra @frozenhelium

**Comment by szabozoltan69** [comment]
Deployed to Staging via https://github.com/IFRCGo/go-api/pull/1758

**Comment by szabozoltan69** [comment]
Decision:
 we'll make for now "cache for non-logged-in users", 10 minutes in staging an 1 minute on prod.
@batpad @tovari

**Comment by szabozoltan69** [comment]
Done via https://github.com/IFRCGo/go-api/pull/1799
