### ISSUE TITLE
Multiple accounts with the same email

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#1478]
In case multiple accounts are registered with the same email, and one of the accounts is inactive, then the user can't login with the other (active) accounts either.

**Comment by szabozoltan69** [comment]
The normal registration process does not allow to have an already existing email address. The mentioned situation can occur only via email address change. What about not allowing the change to an existing address? Otherwise, if there are multiple identities of the user with different access level, how to decide which one does s/he want to use?
