### ISSUE TITLE
Include DREF/Appeal admin form UI for emergencies

### ISSUE THREAD

**Issue by dereklieu** [IFRCGo/go-api#169]

**Comment by dereklieu** [comment]
Since appeals are reverse relations to emergencies, they are not showing up in the emergency admin. This should be a simple fix, cc @matthewhanson.

**Comment by matthewhanson** [comment]
But they should continue to also have their own admin page (in addition to inline under Event)?

**Comment by matthewhanson** [comment]
Work-around for now is to use the Appeals form to attach an Appeal to an Emergency.

Appeals have a ForeignKey to the Event, so the Admin form allows you to create new Appeals from the Event. In order to be able to select an Appeal from the Event, it would have to have to be a ManyToMany relationship, but this would allow Appeals to be linked to multiple Events and you would see all the Appeals in the select box under Event.
