### ISSUE TITLE
[PROD] Project endpoint - too much queries

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-api#1699]
## Issue
There are incredible quantity of unnecessary queries on backend - if user is logged in.
Was discovered via DjagoDebugToolbar while implementing https://github.com/IFRCGo/go-api/issues/1693 – but it was also actual before this change.

.../api/v2/project/
not logged in:2336.08 ms (3626 queries including 3617 similar and 3554 duplicates )
logged in:5479.40 ms (8169 queries including 8155 similar and 8142 duplicates )

.../api/v2/project/198/
not logged in:20.18 ms (7 queries )  !!! GOOD !!! The others should be like this also
logged in:2965.70 ms (4555 queries including 4541 similar and 4501 duplicates )

Mainly this kind of queries are repeated:
SELECT ••• FROM "api_country" WHERE "api_country"."id" = 14 LIMIT 21
4539 similar queries. Duplicated 68 times.

**Comment by szabozoltan69** [comment]
If you have any idea, please tell it, dear @thenav56

**Comment by batpad** [comment]
This is a really good catch and seems like it should be just missing `select_related`, `prefetch_related` type stuff somewhere? @thenav56 do you think you'd be able to look?

**Comment by thenav56** [comment]
Hi there, I looked around and most of the query is due to the form rendered in the DRF `HTML form`.

Basically, due to this line, https://github.com/IFRCGo/go-api/blob/develop/api/models.py#L261 Django has to fetch country causing N+1 query.


There is one prefetch missing from the project. This diff should fix for now. @szabozoltan69 Could you add this to your existing PR?
```diff
diff --git a/deployments/drf_views.py b/deployments/drf_views.py
index 38f13638..3ba40ee9 100644
--- a/deployments/drf_views.py
+++ b/deployments/drf_views.py
@@ -373,7 +373,7 @@ class ProjectViewset(
     viewsets.ModelViewSet,
 ):
     queryset = Project.objects.prefetch_related(
-        'user', 'reporting_ns', 'project_districts', 'event', 'dtype', 'regional_project', 'annual_splits',
+        'user', 'project_country', 'reporting_ns', 'project_districts', 'event', 'dtype', 'regional_project', 'annual_splits',
     ).all()
     filterset_class = ProjectFilter
     serializer_class = ProjectSerializer
```

Tip:
We can see which line of code is triggering the fetch using the Django toolbar. By clicking the `+` before the SQL statement which will show more detail and we can scroll down to the bottom of that block to see where the fetch is triggered and by what.
![2023-03-08-115837](https://user-images.githubusercontent.com/7059255/223634179-b1f27a69-2ce6-4fba-b3cb-254eb2b93308.png)
![2023-03-08-120122](https://user-images.githubusercontent.com/7059255/223634200-9923b51c-4b88-4023-94d0-b26d5305744b.png)

**Comment by szabozoltan69** [comment]
Good catch! 
In general is it true, that M2M needs prefetch-related and ForeignKey needs select-related?
The changes are collecting in https://github.com/IFRCGo/go-api/pull/1701

**Comment by thenav56** [comment]
>  In general is it true, that M2M needs prefetch-related and ForeignKey needs select-related?

Yes, but only if we are using them. Else we will be over-fetching data.

> The changes are collecting in https://github.com/IFRCGo/go-api/pull/1701

Thanks, Could you also mention this Issue on that PR after adding them there?

**Comment by szabozoltan69** [comment]
Maybe "__all__" should be changed to an explicit field name list.
