### ISSUE TITLE
Expose 'updated_at' field in the /personnel endpoint

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-api#1716]
Please expose the `updated_at` field from the `deployments_personneldeployment` table in the /personnel API endpoint.

https://dsgocdnapi.azureedge.net/static/database/tables/deployments_personneldeployment.html

This will allow to import only new and updated deployments to the OCHA site.

**Comment by szabozoltan69** [comment]
Due to the /personnel API endpoint uses the [deployments_personnel](https://dsgocdnapi.azureedge.net/static/database/tables/deployments_personnel.html) table, it does not have own updated_at field. But joining to the above mentioned `deployments_personneldeployment` table we can do the task. But this way the query expression will be deployment__updated_at.
So in an example query one can use for "greater than":
...deployment__updated_at__gt=2022-10-28T12:27:50...

**Comment by szabozoltan69** [comment]
Can be tested on Staging
