### ISSUE TITLE
Additional Fields for FACT/RDRT/RIT

### ISSUE THREAD

**Issue by ascalamogna** [IFRCGo/go-api#181]
If possible, add the following fields:

Name, Role, Society Deployed From, start date, end date

We would need the ability to have multiple entries with these fields under a FACT or RDRT/RIT. You can have multiple people from different societies with different end and start dates as part of the same FACT, RDRT/RIT.

**Comment by dereklieu** [comment]
@ascalamogna thanks, this is helpful.

So to reiterate, FACTs and RDRT/RITs should function similarly to ERU Owners, where each record can have multiple records (aka people) associated with it?

Are there any existing fields from FACTs and RDRT/RITs that we can now remove as duplicates? For example, those both have start date and end date. Is that duplicative now that each "person" in a FACT will have their own start/end dates?

These records also have country, region, event, disaster type, person, role, and comments. I'm guessing person/role can now be removed since there will be multiple people?

Lastly, can HeOps stay the same as it currently is?

**Comment by ascalamogna** [comment]
HeOps can stay exactly as is.

FACT and RDRT/RIT can function similar to the ERU Owners. We can remove person and role. I believe we can also remove start/end date but I'm double checking on that.

**Comment by ascalamogna** [comment]
@dereklieu we should keep start date for the entire FACT and RDRT but we do not need an overall end date for either since that will be when the last individual's end date hits.

**Comment by ascalamogna** [comment]
@dereklieu we should also add the disaster each ERU is being deployed to.
