### ISSUE TITLE
Homepage table - API - funding level

### ISSUE THREAD

**Issue by k-som** [IFRCGo/go-api#205]
(Marked as a question, but more a flag)

Hi Derek,

I've looked through active emergency appeals in the homepage table and noticed relatively small discrepancies in funding level between GO and BO. It can be 100 CHF, it can be 10 000 CHF (in the vast majority of cases funding level is higher on GO than in BO). What's the frequency of BO/GO update? If there's one working day delay then the difference may come from the exchange rate adjustment, but that's only my assumption - will check the figures again tomorrow to confirm if that's the 'problem' or if there's something wrong with BO-GO connection.

Thanks!

**Comment by dereklieu** [comment]
Hey @k-som - the sync happens every hour. I've just checked the production API and it's been running steadily since I deployed it last night. If you're noticing small discrepancies, I wonder if there's some error of logic that's happening with the syncing script. 

Also, we're not doing any adjustments with exchange rates, we're showing the numbers as they come through.

If you point me to a few examples of this discrepancy, I can look into what's happening. If you want to query the endpoint directly, you can do so in your browser (having a json viewer extension like [this one for Chrome](https://chrome.google.com/webstore/detail/json-viewer/gbmdgpbipfallnflgajpaliibnhdgobh?hl=en-US) will help format the response to be more readable).

Here are some example queries:

First 20 appeals, ordered by start date:
[https://prddsgocdnapi.azureedge.net/api/v1/appeal/?order_by=-start_date](https://prddsgocdnapi.azureedge.net/api/v1/appeal/?order_by=-start_date)

Appeal by appeal code:
[https://prddsgocdnapi.azureedge.net/api/v1/appeal/?code=MDRMG013](https://prddsgocdnapi.azureedge.net/api/v1/appeal/?code=MDRMG013)

Appeal by appeal id:
[https://prddsgocdnapi.azureedge.net/api/v1/appeal/?aid=14561](https://prddsgocdnapi.azureedge.net/api/v1/appeal/?aid=14561)

**Comment by k-som** [comment]
Thanks! 

For the exchange rate, I meant that there might be some adjustments on the Federation's end (not sure, though...). 

For example, first five appeals (_BO vs GO_):
* Etiophia - Drought (MDRET016): **3,278,379 and same for GO**,
* Uganda - Population Movement (MDRUG038): **2,202,334 vs 2,202,997**,
* DR Congo - Population Movement (MDRCD023): **88,906 vs 88,955**,
* Bangladesh - Cyclone Mora (MDRBD020): **905,057 vs 904,726**,
* Philippines - Tropical Storm Tembin (MDRPH026): **615,175 vs 614,362**.
As you can see, the discrepancies are really small - that's why I'm wondering what causes them.

**Comment by dereklieu** [comment]
@k-som does the BO data get updated frequently? I wonder if we're not catching the updates, only the initial figures at the time we first ingest this data. In that case we might need to change the syncing script.

**Comment by k-som** [comment]
@dereklieu let me send an email to our IT, we'll try to figure it out on our end first - maybe there's no need to bother you. Will revert to you once I've got the answer from them.

**Comment by szabozoltan69** [comment]
This issue seems to be outdated.
