### ISSUE TITLE
Region api call does not show region name

### ISSUE THREAD

**Issue by SimonbJohnson** [IFRCGo/go-api#289]
For name it repeats the region code
https://prddsgocdnapi.azureedge.net/api/v2/region/

**Comment by szabozoltan69** [comment]
Well, it's not easy to fix, because it is "wired in" the whole API/frontend logic.

In models.py we see: https://github.com/IFRCGo/go-api/blob/master/api/models.py#L36-L46
So there are real "names" for regions, but they are used only as constants in the program (for signing integers). The API itself gives integers (as names) joined to the (same) id-s.

I think it's easier and safer not to change this behavior now. If somebody wants to see the real region names, they are on the front page of go.ifrc.org (in Regions submenu).

**Comment by SimonbJohnson** [comment]
I would suggest adding it in as a new field.  We can't expect every system that wants to use the API especially outside of the organisation to hard the values in.

**Comment by szabozoltan69** [comment]
Good idea! What do you thing about rname or region_name?

**Comment by SimonbJohnson** [comment]
region_name is good!

**Comment by szabozoltan69** [comment]
You can now test it:
https://dsgocdnapi.azureedge.net/api/v2/region/

**Comment by SimonbJohnson** [comment]
Looks great. Cheers!

**Comment by szabozoltan69** [comment]
Thank you! :-)
