### ISSUE TITLE
/docs refreshing

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/go-api#408]
The API docs seems to be outdated, in the server log I see:

[29/May/2019 07:19:47] "GET /docs HTTP/1.1" 301 0
/usr/local/lib/python3.6/site-packages/django_filters/rest_framework/backends.py:93: UserWarning: <class 'per.drf_views.**FormViewset**'> is not compatible with schema generation
 ...UserWarning: <class 'per.drf_views.**FormCountryViewset**'> is not compatible with schema generation
...UserWarning: <class 'per.drf_views.**FormDataViewset**'> is not compatible with schema generation
  ...UserWarning: <class 'api.drf_views.**ProfileViewset**'> is not compatible with schema generation
...UserWarning: <class 'notifications.drf_views.**SubscriptionViewset**'> is not compatible with schema generation
...UserWarning: <class 'api.drf_views.**UserViewset**'> is not compatible with schema generation
  "{} is not compatible with schema generation".format(view.__class__)

How could we refresh these?

https://www.django-rest-framework.org/topics/documenting-your-api/

**Comment by batpad** [comment]
@szabozoltan69 so the reason this is happening is this:

All these ViewSets attempt to access self.request inside a custom get_queryset method, for example: https://github.com/IFRCGo/go-api/blob/master/api/drf_views.py#L323 - you will see a similar pattern for all these ViewSets where you are getting these errors.

The problem is, the Rest Framework Swagger documentation uses "Viewset Introspection" and tries to run the views as "fake views" when generating the documentation to automatically figure out the documentation from the views. The problem is, when the documentation generator runs in this "fake" mode, there is no "request" object that gets passed to the views, and hence when the documentation generator tries to "get_queryset", it would get an error since the get_queryset() methods here depend on a request object.

The best looking solution I have found so far is to do something like this inside the `get_queryset()` methods where this problem is happening: https://github.com/axnsan12/drf-yasg/issues/333#issuecomment-474883875

Let me know if you're able to try this out and see if there's any luck, else I can look at it further.

Some links where people have similar problems:

https://github.com/axnsan12/drf-yasg/issues/267
https://github.com/allisson/django-rest-framework-role-filters/issues/5
https://github.com/carltongibson/django-filter/issues/966

The solution outlined in https://github.com/axnsan12/drf-yasg/issues/333#issuecomment-474883875 seems probably be the best way to handle this. Let me know if this makes sense.

**Comment by szabozoltan69** [comment]
Thank you so much @batpad. So this is not an "outdating" fenomene, but comes from the twisted queryset definition.

I'll check the solutions you offered, I appreciate them!

**Comment by szabozoltan69** [comment]
With the help of your links (and [this](https://www.calazan.com/how-to-retrieve-the-name-of-the-calling-module-in-python/)) I found a solution.

I could not use (litteraly or almost-litteraly) the https://github.com/axnsan12/drf-yasg/issues/333#issuecomment-474883875 solution, and I could not figure out (even with pdb) what should I write instead of the swagger fake view.

I needed information of the "caller" module:
/usr/local/lib/python3.6/site-packages/django_filters/rest_framework/**backends**.py:93
So finally I imported inspect and used this code:
```
    def get_queryset(self):
        if inspect.getmodulename(inspect.stack()[1][1]) == 'backends':
            return Form.objects.none()

Due to the "inspect" it has quite a huge resource requirement, so maybe I shall omit all these (and wear patiently the warning messages in the log).

**Comment by batpad** [comment]
Zoli, oh wow, yea, that seems quite intense :-)

That is indeed unfortunate :-( - yes, we can re-open maybe and look for
another solution if this is turning out to be a big problem.

Nice find though with that fix!

Cheers,
Sanjay
