### ISSUE TITLE
Review/refactor of GO code base - master ticket

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-api#526]
To ensure consistency of coding structure for different modules.

**Comment by nanometrenat** [comment]
This is master ticket - @batpad to add links to the various refactor tickets.

**Comment by batpad** [comment]
- https://github.com/IFRCGo/go-api/issues/541
 - https://github.com/IFRCGo/go-frontend/issues/815
 - https://github.com/IFRCGo/go-frontend/issues/861 (this is not purely a refactor, since it includes more robust error handling / actual improvement for user experience)
 - https://github.com/IFRCGo/go-frontend/issues/862
 - https://github.com/IFRCGo/go-frontend/issues/863

@necoline @thenav56 @frozenhelium can I ask you to please review these - for tickets that you have filed, if possible, please try and give a brief "lay man's explanation of why this is important to do" + an idea or urgency and effort. Also, I do feel we are still missing some critical refactor tickets - for eg. hard-coding of database elements on the frontend, etc. which are probably pretty critical to solve. I will also spend some time thinking about and adding to this, but would be great if everyone could take a little time out to think about this and add tickets for refactors we feel are especially important.

**Comment by GregoryHorvath** [comment]
@batpad should we keep this open?

**Comment by nanometrenat** [comment]
@batpad @frozenhelium @tovari did this ticket (and/or linked tickets, and/or tickets with "refactor" label in all repos) get sorted as part of the web rewrite?  Or does it need to stay open?  Be good to be clear what work is still required.
