### ISSUE TITLE
Simplify CSV Output for Event end-point

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#708]
Currently, the emergency API end-point, when returned as CSV, generates separate columns for every field report attached to the emergency. This is creating an inordinate and unmanageable amount of columns.

We should simplify the CSV output for the Emergency API so that it only returns summarized information for the field reports - perhaps just two fields:

 - Has Field Reports - simple `yes` or `no`
 - Field Report IDs - comma separated list of field report IDs

These changes should only happen on the CSV output, and we should leave the JSON output the same (we do this similarly to how we handle the Field Report serializer conditionally based on the output format).

@nanometrenat please let me know if this ticket is duplicated somewhere, could not find an existing ticket.

cc @GregoryHorvath is this something you might be able to take on?

**Comment by nanometrenat** [comment]
Thanks @batpad that sounds great - I hadn't realised that it was simple to treat csv output differently to json - excellent solution.

Above 2 fields sound perfect.  The other thing that would be amazing (though would be an additional requirement, and may not be feasible, so not critical if too hard/risky), would it be possible to add an additional new field Has COVID Field Report ?  Would be really helpful for our dashboards but we can always do a join if not poss.  Many thanks

**Comment by nanometrenat** [comment]
Interestingly, I did not realise that the "mini" event endpoint was even an option!  Interested to know how/where it is used:  https://goadmin.ifrc.org/docs/#event-mini_events

**Comment by nanometrenat** [comment]
Following Monday's meeting, standing by for a proposed new schema for review - thanks!

**Comment by kamicut** [comment]
So for the Events API, the included data that are larger objects are the following:
- Appeals
- Field Reports
- Countries

For countries, we can use the `database id` as well as an iso code or country name for legibility. I'm not too familiar with the structure of the Appeals and Field Reports but they each have a separate `aid` and `rid` that is different from the id.

Here's a sample output of the CSV with the current code:

|appeals.id|auto_generated                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |countries.id                 |countries.name|created_at                    |disaster_start_date          |dtype.id                     |dtype.name|dtype.summary        |field_reports.id|glide             |id     |ifrc_severity_level|is_featured          |is_featured_region|name                |num_affected                                                                                  |parent_event  |slug          |summary|updated_at|
|----------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------|--------------|------------------------------|-----------------------------|-----------------------------|----------|---------------------|----------------|------------------|-------|-------------------|---------------------|------------------|--------------------|----------------------------------------------------------------------------------------------|--------------|--------------|-------|----------|
|          |TRUE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |14, 285                      |Afghanistan, Africa Region|2020-05-26T04:22:35.314124Z   |2020-05-13T00:00:00Z         |15                           |Fire      |                     |11806           |                  |3559   |Green              |FALSE                |FALSE             |a                   |                                                                                              |              |              |       |2020-06-05T02:52:01.017850Z|
|          |TRUE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |1                            |Ukraine       |2019-05-21T09:50:01.315999Z   |2019-05-21T09:50:01.192943Z  |12                           |Flood     |                     |11805           |                  |3558   |Green              |FALSE                |FALSE             |Flooding in Western Ukraine|                                                                                              |              |              |       |2019-05-21T09:50:01.316015Z|
|          |TRUE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |71                           |Georgia       |2019-05-17T15:01:16.893454Z   |2019-05-17T15:01:16.790122Z  |27                           |Pluvial/Flash Flood|                     |11804           |                  |3557   |Green              |FALSE                |FALSE             |Floods in Kakheti Region, Georgia|                                                                                              |              |              |       |2019-05-17T15:01:16.893472Z|
|          |TRUE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |62                           |El Salvador   |2019-05-17T13:44:57.703203Z   |2019-05-17T13:44:57.468765Z  |2                            |Earthquake|                     |11803           |                  |3556   |Green              |FALSE                |FALSE             |SISMO magnitud 5.9 con replicas en El Salvador|                                                                                              |              |              |       |2019-05-17T13:44:57.703218Z|
|          |TRUE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |112                          |Mali          |2019-05-16T21:30:46.512665Z   |2019-05-16T21:30:46.228676Z  |12                           |Flood     |                     |11802           |                  |3555   |Green              |FALSE                |FALSE             |Ce jeudi  16 mai 2019, une grande inondation à Bamako: bilan provisoire: 14 morts .|                                                                                              |              |              |       |2019-05-16T21:30:46.512679Z|
|          |TRUE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |133                          |Papua New Guinea|2019-05-16T02:44:19.045155Z   |2019-05-16T02:44:18Z         |2                            |Earthquake|                     |11800           |                  |3553   |Green              |FALSE                |FALSE             |7.5 scale Earthquake - Papa New Guinea|250                                                                                           |              |              |<p><span style="font-family: Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 16px;">Quakes measures 7.7 richter scale and much closer to East New Britain, 28 km from Kokopo/Rabaul. It occurs at 22:58 pm, 14 May 2019. Tsunami warning was issued for the coastal areas of New Britain but has since lapsed. The main of Gazelle Peninsula (Kokopo and Rabaul areas) was severely shaken from the earthquake, however, there no major reports of any casualties, infrastructure loss/damage. There were reports of minor landslips along the main trunk roads and fallen goods of retailers and households including a few broken water tanks. There has a been a major power black out since 11pm last night, PNG Power has met this morning to troubleshoot and slowly reconnect back in major areas of ENB. Provincial authorities have dispatched teams to conduct assessments in the 4 x districts of ENB as precautionary. If there any major issues, they will compile by 2pm today to be addressed by PDC and suggests way forward. I have to confirm reports from Duke of York isles which are closer to the epicentre. Have gathered from our provincial teams that went out today and reported back that few places on the island experienced damages. Nabual, Watara, Kibil are names of the three locations. Almost 50 families were affected (will have to verify) and an alleged injury to an elderly disable women from Kibil that a collapsed roof from a semi permament building has fallen onto of her.</span></p>|2019-05-16T15:21:09.296404Z|
|3180      |TRUE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |160                          |Sri Lanka     |2019-05-16T02:19:24.336592Z   |2019-05-16T02:19:24Z         |7                            |Civil Unrest|                     |11799           |                  |3552   |Green              |FALSE                |FALSE             |Easter Sunday Attack in Sri Lanka|3000                                                                                          |              |              |<p>This Call for Support seeks a total of 2 million Swiss francs to enable the International Federation of Red Cross and Red</p> <p>Crescent Societies (IFRC) to support the Sri Lanka Red Cross Society to deliver assistance and support 41,000 people</p> <p>directly and 5 million people indirectly over 12 months. This work will focus on the following areas: Livelihoods and</p> <p>Basic needs, Health, and Protection, Gender and Inclusion (PGI). The planned response reflects the current situation</p> <p>and information available at the time of the evolving operation, and will be adjusted based on further developments and</p> <p>detailed assessments. The plan will complement the activities covered by the DREF allocation, details can be found in</p> <p>the EPOA.</p>|2019-05-16T08:14:17.373168Z|
|          |TRUE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |222                          |Israel        |2019-05-15T17:59:40.011132Z   |2019-05-15T17:59:39.947733Z  |2                            |Earthquake|                     |11798           |                  |3551   |Green              |FALSE                |FALSE             |On May 15th at 19:53 an earthquake was felt in Israel, no reports of damage or casualties.|                                                                                              |              |              |       |2019-05-15T17:59:40.011147Z|
|          |TRUE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |194                          |Mongolia      |2019-05-15T07:34:27.182236Z   |2019-05-15T07:34:26Z         |14                           |Cold Wave |                     |11797           |                  |3550   |Green              |FALSE                |FALSE             |6 dead in an active snowstorm in Mongolia|500                                                                                           |              |              |       |2019-05-16T15:33:03.391751Z|
|          |TRUE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |76                           |Guatemala     |2019-05-14T23:24:54.694277Z   |2019-05-14T23:24:54.179557Z  |20                           |Drought   |                     |11796           |                  |3549   |Green              |FALSE                |FALSE             |Sequía en Guatemala |                                                                                              |              |              |       |2019-05-14T23:24:54.694294Z|

**Comment by batpad** [comment]
@kamicut this is looking good to me! @nanometrenat could you look at the CSV sample above, and happy to have a follow-up chat any time.

@kamicut I see that in the CSV posted, there is only always one field report, country, etc. - is it possible to output with an example where there are multiple ids / names? I assume these values will be comma-separated inside a single cell?

**Comment by GregoryHorvath** [comment]
@kamicut :+1: I like the latest approach you went in the latest code, so I'm following that for the Tableau WDC. I'd say we should definately include `summary` for the `fieldreport`s and `name` for the `appeal`s.

cc @batpad

**Comment by LukeCaley** [comment]
@nanometrenat could you review and comment on the schema proposed please?

**Comment by batpad** [comment]
The new CSV schema for Events is on staging - it will no longer return multiple columns for related items. Would be great to get a review, and also some discussion on how we inform users, etc.

**Comment by LukeCaley** [comment]
@nanometrenat would you have time to UAT this please?  If possible also to work with @JonathanGarro on documenting and communicating the changes to users.

**Comment by batpad** [comment]
@LukeCaley - this ticket and @kamicut's example CSV output above describes the changes to the Emergencies CSV end-point. We have made the output always a fixed amount of columns, and returned things like country ids as comma separated values. This should make general CSV processing much more convenient, and will avoid problems we were having with a massive amount of columns in the output CSV.

This will also improve performance of the CSV end-point. This is however, a **breaking** API change and anyone depending on the Emergencies CSV export will need to account for this change.

Happy to work with @JonathanGarro on figuring out how best to communicate these changes to users.
